server:
  port: 8083

spring:
  application:
    name: ORDER-SERVICE


  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka




logging:
  level:
    org.springframework.cloud.openfeign: DEBUG

