spring:
  application:
    name: NOTIFICATION-SERVICE

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka